//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchWihAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Employeeid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Hiredata { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Cv { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Departmentid { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
