//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchWihAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int Productid { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<int> UnitsInstook { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Categoryid { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
